coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 85%

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
